### PR TITLE
Add stignore support to nautilus

### PR DESCRIPTION
**Pull request by TechupBusiness**
I couldnt directly convert the go-code to python, so I ended up by writing the logic by myself. It should cover (all?) the cases mentioned in the documentation. But tests are welcome! :)

Feedback welcome!

### CODE REVIEW

**Comment by TechupBusiness** [comment]
@kozec here is another merge request :) Feedback and tests are welcome!

**Comment by AudriusButkevicius** [comment]
I think the logic here does not match, as we stop processing ignores on the first hit.

**Comment by kozec** [comment]
> For example: how could I improve the stignore-loading? Right now it's only reloading the file when I kill nautilus (nautilus -q) or when cb_syncthing_folder_added is called.

I would go with remembering mtime of .stignore file and checking it every time when folder is refreshed. That should work with almost no memory footprint unless someone has literally hundreds of synchronized folders.


> Do you have an idea for icons that I could use for ignored files (the offline icon would be good but can be confusing sometimes)

How about not displaying any icon for those files? Or maybe [transparent logo](https://user-images.githubusercontent.com/1282500/67889656-8a224280-fb4f-11e9-86fd-1d2cf37ab726.png) to communicate similar message as when IDE displays half-transparent icons for .gitignore-d files.

**Comment by TechupBusiness** [comment]
> I think the logic here does not match, as we stop processing ignores on the first hit.

Thanks for your feedback! Are you referring to this section?
```python
# Check patterns for repo
for regex in self.ignore_patterns[repo]:
	# Performance advantage to check exclude before match (for the case is_ignored == True)
	if regex['exclude']:
		if is_ignored and regex['compiled'].match(path):
			is_ignored = False
	else:
		if not is_ignored and regex['compiled'].match(path):
			is_ignored = True
```
It's true that it continues to check further condition, but only the excludes. You mean the case that a file:
1. it is ignored
1. excluded from ignore
1. there is no further processing now: a potential next ignore would not ignore the excluded (from ignore) file
To solve this issue I could simply change one line of the above code to:
```python
# Check patterns for repo
for regex in self.ignore_patterns[repo]:
	# Performance advantage to check exclude before match (for the case is_ignored == True)
	if regex['exclude']:
		if is_ignored and regex['compiled'].match(path):
			return False
	else:
		if not is_ignored and regex['compiled'].match(path):
			is_ignored = True
```
This way it stops further ignore processing when it hits a exclude match for a file. Then all following ignore patterns will be skipped.

**Comment by TechupBusiness** [comment]
> > For example: how could I improve the stignore-loading? Right now it's only reloading the file when I kill nautilus (nautilus -q) or when cb_syncthing_folder_added is called.
> 
> I would go with remembering mtime of .stignore file and checking it every time when folder is refreshed. That should work with almost no memory footprint unless someone has literally hundreds of synchronized folders.

Sounds good! Would you go for another callback or is cb_syncthing_folder_added the right place? I noticed for example the events:
- folder-data-changed
- folder-scan-finished

> > Do you have an idea for icons that I could use for ignored files (the offline icon would be good but can be confusing sometimes)
> 
> How about not displaying any icon for those files? Or maybe [transparent logo](https://user-images.githubusercontent.com/1282500/67889656-8a224280-fb4f-11e9-86fd-1d2cf37ab726.png) to communicate similar message as when IDE displays half-transparent icons for .gitignore-d files.

Hm transparent emblem sounds good. Maybe we could use a green emblem with opacity < 1 for ignored directories that contains non-ignored files and remove any emblem on completely ignored files/folder (as implemented right now) or use this grey emblem with opacity < 1 (to indicate to the user that the file is within a syncthing folder)? Could you give me a hint how to add this emblem? Would save me some time, I don't understand the installation/setup completely yet :)

**Comment by kozec** [comment]
`folder-scan-finished` is probably better place, IIRC, `folder-added` fires only once, so you wouldn't have opportunity to reload .stignore at all.

> Could you give me a hint how to add this emblem? Would save me some time, I don't understand the installation/setup completely yet :)

Just adding it to `icons/` directory should be enough, [setup.py already installs everything with "emblem-" prefix from there.](https://github.com/syncthing/syncthing-gtk/blob/master/setup.py#L95)

**Comment by TechupBusiness** [comment]
> Just adding it to `icons/` directory should be enough, [setup.py already installs everything with "emblem-" prefix from there.](https://github.com/syncthing/syncthing-gtk/blob/master/setup.py#L95)

Thanks! For development (with apt installation) I needed to copy the icon with proper naming scheme to `/usr/share/icons/hicolor/64x64/emblems` (found via `dpkg-query -L syncthing-gtk`).

And then run: `sudo update-icon-caches /usr/share/icons/*` to refresh the cache manually.

I made the "ignored-parent-path" 50% transparent. Do you think @kozec its enough for clearly seeing the difference in the folder structure?
image
The second folder is ignored but it contains non-ignored content (on any deeper level).

**Comment by TechupBusiness** [comment]
> I think the logic here does not match, as we stop processing ignores on the first hit.

@AudriusButkevicius could you please give some more details of how syncthing is doing things different? Did you mean https://github.com/syncthing/syncthing-gtk/pull/538#issuecomment-548151446 ? Thanks!

**Comment by kozec** [comment]
> Do you think @kozec its enough for clearly seeing the difference in the folder structure?

Yes, I can see difference clearly.

**Comment by TechupBusiness** [comment]
Found out that stignore behaves unfortunately different to gitignore... not really intuitive...

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Comment by TechupBusiness** [comment]
I'm still using it and it works like a charm. Would you merge it @kozec ? It's not perfect but better than without :)

**Comment by kozec** [comment]
Sorry about that bot, he is really stealthy and doesn't generate email notifications.

I'll do brief test just to check it doesn't explode with Nemo and merge it.

**Pull request merged**
